{
 "title": "play.grafana.org » Influx: Bar Charts and Time Series using Mixed queries",
 "tags": [
  "example",
  "grafana-toolbox",
  "play.grafana.org"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 7, "x": 0, "y": 0 }, "options": { "content": "# InfluxQL" } },
  { "type": "text", "gridPos": { "h": 2, "w": 7, "x": 7, "y": 0 }, "options": { "content": "# SQL" } },
  { "type": "text", "gridPos": { "h": 2, "w": 7, "x": 14, "y": 0 }, "options": { "content": "# Flux" } },
  {
   "title": "More InfluxQL examples here, including variables, tables and pie charts",
   "type": "dashlist",
   "gridPos": { "h": 1, "w": 7, "x": 0, "y": 2 }
  },
  {
   "title": "More FlightSQL examples here, including variables, tables and pie charts",
   "type": "dashlist",
   "gridPos": { "h": 1, "w": 7, "x": 7, "y": 2 }
  },
  {
   "title": "More Flux examples here, including variables, tables and pie charts",
   "type": "dashlist",
   "gridPos": { "h": 1, "w": 7, "x": 14, "y": 2 }
  },
  {
   "title": "Hourly Demand using InfluxQL",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "mwatth" } },
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"ElectricPowerOperations\" WHERE (\"type\"::tag = 'Demand' AND \"region\"::tag =~ /(Florida|New York)/) AND $timeFilter GROUP BY region, time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "Hourly Demand using FlightSQL",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "mwatth" } },
   "targets": [
    {
     "queryText": "SELECT * FROM \"ElectricPowerOperations\" WHERE \"type\" IN ('Demand') AND \"region\" IN ('Florida', 'New York') AND $__timeRange(time)"
    }
   ]
  },
  {
   "title": "Hourly Demand using Flux",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "mwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"EIAtest7\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricPowerOperations\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"Demand\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"Florida\" or r[\"region\"] == \"New York\")\r\n  |> group(columns: [\"region\", \"_measurement\"], mode:\"by\") \r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"HourlyData\")"
    }
   ]
  },
  {
   "title": "Query for above graph:",
   "type": "text",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 13 },
   "options": {
    "content": "SELECT sum(\"value\")\r\nFROM \"ElectricPowerOperations\"\r\nWHERE (\"type\"::tag = 'Demand'\r\nAND \"region\"::tag =~ /(Florida|New York)/)\r\nAND $timeFilter\r\nGROUP BY region, time($__interval) fill(previous)"
   }
  },
  {
   "title": "Query for above graph:",
   "type": "text",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 13 },
   "options": {
    "content": "SELECT * FROM \"ElectricPowerOperations\"\r\nWHERE \"type\" IN ('Demand')\r\nAND \"region\" IN ('Florida', 'New York')\r\nAND $__timeRange(time)"
   }
  },
  {
   "title": "Query for above graph:",
   "type": "text",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 13 },
   "options": {
    "content": "from(bucket: \"EIAtest7\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricPowerOperations\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"Demand\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"Florida\" or r[\"region\"] == \"New York\")\r\n  |> group(columns: [\"region\", \"_measurement\"], mode:\"by\") \r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"HourlyData\")"
   }
  },
  {
   "title": "Daily Demand using InfluxQL",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mwatth" } },
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"ElectricPowerOperations\" WHERE (\"type\"::tag = 'Demand' AND \"region\"::tag =~ /(Florida|New York)/) AND $timeFilter GROUP BY region, time(1d)"
    }
   ]
  },
  {
   "title": "Daily Demand using FlightSQL",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mwatth" } },
   "targets": [
    {
     "columns": [
      { "value": "region" }
     ],
     "queryText": "SELECT date_Bin(INTERVAL '1 day', time, TIMESTAMP '1970-01-01 00:00:00Z') AS time, sum(\"value\") AS sum_value, region\n FROM \"ElectricPowerOperations\" WHERE \"type\" IN ('Demand') AND \"region\" IN ('Florida', 'New York') AND $__timeRange(time) GROUP BY 1, region\n ORDER BY time ASC",
     "table": "\"ElectricPowerOperations\"",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Daily Demand using Flux",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"EIAtest7\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricPowerOperations\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"Demand\" )\r\n  |> filter(fn: (r) => r[\"region\"] == \"Florida\" or r[\"region\"] == \"New York\")\r\n  |> group(columns: [\"region\", \"_measurement\"], mode:\"by\") \r\n  |> aggregateWindow(every: 1d, fn: sum, timeSrc:\"_start\")  // sums the total used per day\r\n  |> yield(name: \"DailyData\")"
    }
   ]
  },
  {
   "title": "Query for above graph:",
   "type": "text",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 25 },
   "options": {
    "content": "SELECT sum(\"value\")\r\nFROM \"ElectricPowerOperations\"\r\nWHERE (\"type\"::tag = 'Demand'\r\nAND \"region\"::tag =~ /(Florida|New York)/)\r\nAND $timeFilter\r\nGROUP BY region, time(1d)"
   }
  },
  {
   "title": "Query for above graph:",
   "type": "text",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 25 },
   "options": {
    "content": "SELECT date_Bin(INTERVAL '1 day', time, TIMESTAMP '1970-01-01 00:00:00Z')\r\nAS time, sum(\"value\")\r\nAS sum_value, region\r\n FROM \"ElectricPowerOperations\"\r\n WHERE \"type\" IN ('Demand') AND \"region\" IN ('Florida', 'New York')\r\n AND $__timeRange(time)\r\n GROUP BY 1, region\r\n ORDER BY time ASC"
   }
  },
  {
   "title": "Query for above graph:",
   "type": "text",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 25 },
   "options": {
    "content": "from(bucket: \"EIAtest7\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricPowerOperations\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"Demand\" )\r\n  |> filter(fn: (r) => r[\"region\"] == \"Florida\" or r[\"region\"] == \"New York\")\r\n  |> group(columns: [\"region\", \"_measurement\"], mode:\"by\") \r\n  |> aggregateWindow(every: 1d, fn: sum, timeSrc:\"_start\")\r\n  |> yield(name: \"DailyData\")"
   }
  },
  {
   "title": "Average Demand by Hour of Day using SQL",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "mwatth" } },
   "targets": [
    {
     "columns": [
      { "value": "region" }
     ],
     "queryText": "SELECT\n  EXTRACT(HOUR FROM \"time\") AS hour,\n  \"region\",\n  \"time\",\n  \"type\",\n  \"value\"\nFROM \"ElectricPowerOperations\"\nWHERE\n  $__timeRange(time)\n  AND\n  \"value\" IS NOT NULL\n  AND\n  \"region\" = 'Florida'\n  AND \"type\" = 'Demand'\nGROUP BY hour, \"region\", \"time\", \"type\", \"value\"\nORDER BY hour;",
     "table": "\"ElectricPowerOperations\"",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Average Demand by Hour of Day using Flux",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "mwatth" } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\nfrom(bucket: \"EIAtest7\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricPowerOperations\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"Demand\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"Florida\")\r\n  |> group(columns: [\"region\", \"_measurement\"], mode:\"by\") \r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> timeShift(duration: -1h)\r\n  |> map(fn: (r) => ({ r with hour: date.hour(t: r._time) }))  \r\n  |> group(columns: [\"hour\"], mode:\"by\")\r\n  |> mean(column: \"_value\") \r\n  |> group()\r\n  |> sort(columns: [\"hour\"])"
    }
   ]
  },
  {
   "title": "Query for above graph:",
   "type": "text",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 39 },
   "options": {
    "content": "SELECT\r\n  EXTRACT(HOUR FROM \"time\") AS hour,\r\n  \"region\",\r\n  \"time\",\r\n  \"type\",\r\n  \"value\"\r\nFROM \"ElectricPowerOperations\"\r\nWHERE\r\n  $__timeRange(time)\r\n  AND\r\n  \"value\" IS NOT NULL\r\n  AND\r\n  \"region\" = 'Florida'\r\n  AND \"type\" = 'Demand'\r\nGROUP BY hour, \"region\", \"time\", \"type\", \"value\"\r\nORDER BY hour;"
   }
  },
  {
   "title": "Query for above graph:",
   "type": "text",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 39 },
   "options": {
    "content": "import \"date\"\r\n\r\nfrom(bucket: \"EIAtest7\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricPowerOperations\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"Demand\")\r\n  |> filter(fn: (r) => r[\"region\"] == \"Florida\")\r\n  |> group(columns: [\"region\", \"_measurement\"], mode:\"by\") \r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> timeShift(duration: -1h)\r\n  |> map(fn: (r) => ({ r with hour: date.hour(t: r._time) }))  \r\n  |> group(columns: [\"hour\"], mode:\"by\")\r\n  |> mean(column: \"_value\") \r\n  |> group()\r\n  |> sort(columns: [\"hour\"])"
   }
  }
 ]
}